version: "3"
volumes:
  db-data:

services:
  db:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
  web:
    image: healthchecks/healthchecks:latest
    environment:
      - DB_NAME=$DB_NAME
      - DB_PASSWORD=$DB_PASSWORD
      - ALLOWED_HOSTS=$ALLOWED_HOSTS
      - SITE_ROOT=$SITE_ROOT
      - SECRET_KEY=$SECRET_KEY
      - DB=postgres
      - DB_CONN_MAX_AGE=0
      - DB_HOST=db
      - DB_PORT=5432
      - DB_SSLMODE=prefer
      - DB_TARGET_SESSION_ATTRS=read-write
      - DB_USER=postgres
      - DEBUG=False
      - DEFAULT_FROM_EMAIL=healthchecks@example.org
      - DISCORD_CLIENT_ID=
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=True
      - EMAIL_USE_VERIFICATION=True
      - INTEGRATIONS_ALLOW_PRIVATE_IPS=False
      - MASTER_BADGE_LABEL=Mychecks
      - MATTERMOST_ENABLED=True
      - MSTEAMS_ENABLED=True
      - OPSGENIE_ENABLED=True
      - PAGERTREE_ENABLED=True
      - PD_ENABLED=True
      - PING_BODY_LIMIT=10000
      - PING_ENDPOINT=http://localhost:8000/ping/
      - PROMETHEUS_ENABLED=True
      - PUSHOVER_EMERGENCY_EXPIRATION=86400
      - PUSHOVER_EMERGENCY_RETRY_DELAY=300
      - REGISTRATION_OPEN=True
      - ROCKETCHAT_ENABLED=True
      - S3_TIMEOUT=60
      - S3_SECURE=True
      - SHELL_ENABLED=False
      - SITE_NAME='Bossa Nova HealthChecks'
      - SPIKE_ENABLED=True
      - USE_PAYMENTS=False
      - VICTOROPS_ENABLED=True
      - WEBHOOKS_ENABLED=True
      - ZULIP_ENABLED=True
    expose:
      - 8000
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uwsgi /opt/healthchecks/docker/uwsgi.ini'
